version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web-ui:
    build: .
    command: streamlit run web_ui.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
    ports:
      - "8501:8501"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./bot_config.json:/app/bot_config.json
    restart: unless-stopped
    depends_on:
      - trading-bot

  status-api:
    build: .
    command: uvicorn status_api:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    restart: unless-stopped
    depends_on:
      - trading-bot

  coin-analysis-api:
    build: .
    command: python coin_analysis_api.py
    ports:
      - "5001:5001"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    volumes:
      - ./:/app/
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - trading-bot

networks:
  trading-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 124.122.123.0/24
        